version: 2.1

jobs:
  job_one:
    docker:
      - image: cimg/ruby:2.6.8
    steps:
      - checkout
      - run:
          name: "Create a File"
          command: echo "This is data from job_one" > workspace_file.txt
      - persist_to_workspace:
          root: .
          paths:
            - workspace_file.txt

  job_two:
    docker:
      - image: cimg/ruby:3.2
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: "List Workspace Files"
          command: ls -l /workspace
      - run:
          name: "Read Workspace File"
          command: cat /workspace/workspace_file.txt

workflows:
  version: 2
  build:
    jobs:
      - job_one
      - job_two:
          requires:
            - job_one
